name: CI for Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Prepare environment
        run: |
          chmod +x project/test.sh
          chmod +x project/pipeline.sh

      - name: Run tests
        run: |
          cd project
          ./test.sh

