name: CI for Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Add dependencies if any, example:
          # pip install -r requirements.txt

      - name: Run tests
        run: |
<<<<<<< HEAD
          chmod +x project/tests.sh
          .//project/tests.sh
=======
          python -m unittest discover -s ./project -p '*_test.py'



# name: CI for Project Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python 3.10
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.10'

#       - name: Install Python dependencies
#         run: |
#           python -m pip install --upgrade pip

#       - name: Set working directory
#         run: cd project

#       - name: Execute tests
#         run: |
#           chmod +x project/tests.sh
#           ./project/tests.sh
>>>>>>> 2730a81 (Adding report as ipynb file)
